### ISSUE TITLE
Remove the damn .DS_store

### ISSUE THREAD

**Issue by ilyasst** [olivecha/Mini-Tensile#2]

**Comment by ilyasst** [comment]
Done in 8e6de63eb2e86fb39692a1043b2f4ed684967b6a

**Comment by ilyasst** [comment]
It's back ! .DS_store was just pushed back to the repo !

**Comment by olivecha** [comment]
I should add it to Gitignore ?

**Comment by ilyasst** [comment]
Yes, and then delete it using the github app.
Git will not delete a file if it is added to the `.gitignore` **after** it was already added to the repo.
Also, the `.idea` folder seems to be a hidden folder (files and folders that start with a `.` are hidden files in Linux and MacOS) created by your IDE (IntelliJbrains? or maybe Pycharms?), it is only useful for you on your machine, because it is only used by your IDE. It should not be pushed to the repo.
So I'd recommend adding `.idea` to the gitignore too, and then deleting them with the git app (your IDE will recreate it locally, but it will never be pushed online again).

Cheers :)

**Comment by ilyasst** [comment]
Problem was solved, closing the issue.
